# Generated by Django 3.2.15 on 2024-03-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageBase',
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='VideoBase',
        ),
    ]
