# Generated by Django 3.2.15 on 2025-08-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0003_alter_dataset_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='file_path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
