# Generated by Django 3.2.15 on 2025-08-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_app', '0004_auto_20250802_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetfile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
